apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: zvbsbd0vt-nodejs 
  janus-idp.io/tekton: zvbsbd0vt-nodejs
  backstage.io/kubernetes-id: zvbsbd0vt-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: zvbsbd0vt-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml