apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zvbsbd0vt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zvbsbd0vt-nodejs 
  name: zvbsbd0vt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zvbsbd0vt-nodejs 
